### ISSUE TITLE
Request for pretrained model of Table 1

### ISSUE THREAD

**Issue by super233** [lhoyer/DAFormer#12]
Hi, thanks for your awesome work. Can you provide the pretrained model of SegFormer for UDA (58.2) in Table 1?

![image](https://user-images.githubusercontent.com/35358984/155134068-6bf5861a-8735-493b-bbca-5961aae61f45.png)

**Comment by super233** [comment]
One more question, I have noticed that your pretrained models are about `BN` but not `SyncBN`, however, the official pretrained models are all about `SyncBN`.

Have you use some ways to convert model weights from official pretrained models about `SyncBn` into `BN`? Or have you trained the model with `BN` from scratch?

I'm looking forward to your reply. :-)

**Comment by lhoyer** [comment]
The models use BN instead of SyncBN as only one GPU is used for training. 
We have trained the models of Tab. 1 ourselves. You can replicate the training using python run_experimenty.py --exp 1. Please have a look at the [experiments.py#L226](https://github.com/lhoyer/DAFormer/blob/4447661ab92488fb5ece5dd69fb3f7eb62f930c4/experiments.py#L226) for more details.

**Comment by lhoyer** [comment]
I have uploaded the requested checkpoint to Google Drive: https://drive.google.com/file/d/1neppvQVH2kqjS2KSS82llk9iZ3QNry4h/view?usp=sharing

**Comment by super233** [comment]
Thanks very much!
