### ISSUE TITLE
What is the config to run the baseline without any extra method?

### ISSUE THREAD

**Issue by xingchenzhao** [lhoyer/DAFormer#28]
Thank you for the great work! I wonder what is the config to run the baseline using pure transformer without the proposed method?

**Comment by lhoyer** [comment]
Thanks for your interest in our work! All configs used in the paper can be generated using `python run_experiments.py --exp <ID>`. As you seem to refer to table 1, the relevant ID is 1. You can find more details here: https://github.com/lhoyer/DAFormer/blob/master/experiments.py#L223 In order to only train the transformer, you can comment out all architectures except 'segformer' in `models`. To only run UDA training, you can comment out all variants except 'dacs' in `udas`.

**Comment by xingchenzhao** [comment]
Thank you so much for your quick response!!
