### ISSUE TITLE
About RandomCrop on target image

### ISSUE THREAD

**Issue by BinhuiXie** [lhoyer/DAFormer#6]
Hi @lhoyer. Thank you for your wondeful work and detailed code.

Here I have some questions about one of the data transforms. For target image, RandomCrop is applied, as follows:

https://github.com/lhoyer/DAFormer/blob/21c5499f0ee1ea0ecd991003ba4598782d42ec04/mmseg/datasets/pipelines/transforms.py#L547-L556

I find that when `cat_max_ratio < 1` the ground-truth label of target image is also used. However, target ground-truth labels are **unavailable** in the UDA setting. 

Could you please help me out. Thanks again!

**Comment by lhoyer** [comment]
Hi @BinhuiXie,

Thank you for your interest in our work.

This is indeed an unintended side effect from the use of the mmsegmentation
data loader. Thanks or spotting and reporting this bug.

I'll work on a fix and provide updated results. However, I assume that
using pseudo labels for the cat ratio instead of ground truth won't affect
the performance much as the pseudo labels should approximate the cat ratio
of the ground truth very well.

Binhui Xie (谢斌辉) ***@***.***> schrieb am Do., 30. Dez. 2021,
04:08:

**Comment by BinhuiXie** [comment]
Hi @lhoyer, 

You really did marvelous work. I have learnt so much, thanks to you.

**Comment by lhoyer** [comment]
Hi @BinhuiXie,

Thanks a lot. I'm happy that you enjoyed this work.

**Comment by BinhuiXie** [comment]
Congratulations 🎉🎉🎉@lhoyer

**Comment by lhoyer** [comment]
Thanks! :smile:
